#define TK_FUNC                            1
#define TK_ILLEGAL                         2
#define TK_SPACE                           3
#define TK_COMMENT                         4
#define TK_SHOW                            5
#define TK_TABLES                          6
#define TK_SEMI                            7
#define TK_COLUMNS                         8
#define TK_FROM                            9
#define TK_ID                             10
#define TK_DROP                           11
#define TK_TABLE                          12
#define TK_CREATE                         13
#define TK_LP                             14
#define TK_RP                             15
#define TK_INT_TYPE                       16
#define TK_DOUBLE_TYPE                    17
#define TK_STRING_TYPE                    18
#define TK_COMMA                          19
#define TK_DELETE                         20
#define TK_INSERT                         21
#define TK_INTO                           22
#define TK_VALUES                         23
#define TK_SELECT                         24
#define TK_STAR                           25
#define TK_WHERE                          26
#define TK_GROUP                          27
#define TK_BY                             28
#define TK_LIMIT                          29
#define TK_INTEGER                        30
#define TK_AND                            31
#define TK_EQ                             32
#define TK_NE                             33
#define TK_GT                             34
#define TK_GE                             35
#define TK_LT                             36
#define TK_LE                             37
#define TK_LIKE                           38
#define TK_IS                             39
#define TK_NOT                            40
#define TK_NULL                           41
#define TK_ISNOTNULL                      42
#define TK_ISNULL                         43
#define TK_DOUBLE                         44
#define TK_PLUS                           45
#define TK_MINUS                          46
#define TK_UINTEGER                       47
#define TK_UDOUBLE                        48
#define TK_STRING                         49
